name: Apuesta Suprema Mensaje

on:
  workflow_dispatch:

jobs:
  enviar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensaje
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          curl -s "https://api.telegram.org/bot${TOKEN}/sendMessage?chat_id=@apuestasupremax&text=👑%20APUESTA%20SUPREMA%20-%20BOT%20CONECTADO%20CORRECTAMENTE"
