name: Apuesta Suprema Bot

on:
  workflow_dispatch:

jobs:
  enviar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensaje a Telegram
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: echo "Bot preparado"
